services:
  rikka:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /go/src/ictsc-rikka
    command: air -c .air.toml
    ports:
      - ${RIKKA_PORT}:8080
    volumes:
      - .:/go/src/ictsc-rikka:cached
      - .local/pkg:/go/pkg:cached
    restart: always
    depends_on:
      - mariadb
      - redis
      - minio
  mariadb:
    image: mariadb:10.5.10
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_INITDB_CHARSET: utf8mb4
    restart: always
  redis:
    image: redis:6.2.4
    ports:
      - ${REDIS_PORT}:6379
    restart: always
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    ports:
      - ${MINIO_PORT}:9000
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    command: server /data
    restart: always

volumes:
  mariadb:
    driver: local
  go-pkg:
    driver: local
  minio:
    driver: local
