version: "3"

services:
  mariadb:
    image: mariadb:10.5.10
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rikka
      MYSQL_USER: rikka
      MYSQL_PASSWORD: rikka-password
  redis:
    image: redis:6.2.4
    ports:
      - 6379:6379
  go:
    image: golang:1.16
    volumes:
      - ./:/go/src/ictsc-rikka
      - go-pkg:/go/pkg
    working_dir: /go/src/ictsc-rikka
    ports:
      - 8080:8080
    profiles:
      - extra
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    volumes:
      - minio:/data
    command: server /data

volumes:
  mariadb:
    driver: local
  go-pkg:
    driver: local
  minio:
    driver: local
